# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#   instance:
#     prefer-ip-address: true


# logging:
#   level:
#     org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:INFO}
#     org.hibernate.type.descriptor.sql: ${HIBERNATE_BIND_LOG_LEVEL:WARN}
    
# okta:
#   oauth2:
#     issuer: https://integrator-4078265.okta.com/oauth2/default
#     audience: api://default
# spring:
#   zipkin:
#     base-url: http://zipkin-svc:9411
#   sleuth:
#     sampler:
#       probability: 1.0


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
okta:
  oauth2:
    issuer: https://dev-15585796.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
